name: CI

on:
  schedule:
    - cron: 0 0 1 * *
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install shunit2
      - name: Test with shunit2
        run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} ./test
  get-linked-issues:
    name: Get linked issues
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get branch name
        id: get-branch-name
        run: echo "::set-output name=branch::$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}})"
      - name: Get issue numbers separated by commas
        id: get-issues
        uses: mondeja/pr-linked-issues-action@dev
        with:
          repository_owner: mondeja
          repository_name: pr-linked-issues-action-testing
          pull_request: 3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check issue numbers
        run: if [ "${{ steps.get-issues.outputs.issues }}" != "1,2" ]; then exit 1; fi
