name: CI

on:
  schedule:
    - cron: 0 0 1 * *
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install shunit2
      - name: Test with shunit2
        run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} ./test
  get-linked-issues:
    name: Get linked issues
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get branch name
        id: get-branch-name
        run: echo "::set-output name=branch::$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}})"
      - name: Get issue numbers separated by commas
        id: get-issues
        uses: mondeja/pr-linked-issues-action@v2
        with:
          repository_owner: mondeja
          repository_name: pr-linked-issues-action-testing
          pull_request: 6
          owners: true
          add_links_by_content: |
            **Closes**: #{issue_number}
            makes #{issue_number} crazy
            resolves #{issue_number} even if not exists
            [{issue_number}]
            ...{issue_number}..
            #
            # Comments like this must be ignored
            #
            ${issue_number}^
            ({issue_number})
            |{issue_number}|
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check issue numbers
        run: |
          echo "${{ steps.get-issues.outputs.issues }}"
          echo "${{ steps.get-issues.outputs.opener }}"
          echo "${{ steps.get-issues.outputs.others }}"
          echo "${{ steps.get-issues.outputs.null }}"
          if [ "${{ steps.get-issues.outputs.issues }}" != "0,1,2,7,55,57,58,60,77,78" ]; then exit 1; fi
          if [ "${{ steps.get-issues.outputs.opener }}" != "7" ]; then exit 1; fi
          if [ "${{ steps.get-issues.outputs.others }}" != "1,2" ]; then exit 1; fi
          if [ "${{ steps.get-issues.outputs.null }}" != "0,55,57,58,60,77,78" ]; then exit 1; fi
